---

image: Visual Studio 2017

version: 1.4.0.{build}

install:
  - ps: |
      Install-PackageProvider -Name NuGet -Force
      Install-Module -Name Pester -Repository PSGallery -Force

build: false

test_script:
  - ps: |
      $testResultsFilePath = Join-Path -Path $PWD -ChildPath 'TestsResults.xml'
      Push-Location
      Set-Location -Path '.\Tests'
      $testResults = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFilePath -PassThru
      Pop-Location
      $jobUrl = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      $webClient = New-Object -TypeName System.Net.WebClient
      $webClient.UploadFile($jobUrl, $testResultsFilePath)
      if ($testResults.FailedCount -gt 0) {throw "$($testResults.FailedCount) tests failed."}
